language: objective-c
osx_image: xcode9.2
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
script:
- set -o pipefail
- brew install IMcD23/brew/ibuild
- xcodebuild -version
- xcodebuild -showsdks
- carthage build --no-skip-current --verbose
before_deploy:
- set -o pipefail
- carthage archive curl
deploy:
  provider: releases
  api_key:
    secure: U31EXAYWrakI6uBID3j3jbh4JcQJvqpSeZYaMc+HW9165aoF6xRmLjkYDQqfZWIxUQN75LSrupUD1YYXKmPoHPITjYb5n3Vv0805eDnY6Mu5pEBPrEB8dF/++UZq2mVdUuVF+mk05fnz+DEf+/LaoRCw1TxsZBcqMEyVRfG44+6yuQC16W1uooMQP07YLGPdeWmOU+FFRTqNF7dXv/hkc+kMmN6eqKwWBtQCV6EYFy2LR8s1L8OfK4mXuKIpOXNKqhT5m03Jt2lhRlST9jxXWTBFddIAWgGPFt+nCvazp85hgJEy/083oF5YjTeU2SyMzWUtV8kqfRwFg755ekzc/N9F75MW9ghBKMZM8KaZmfWw1QGlan15jskLar0pGfEBDJMjdJT6dKs3zVqiqMBnDm2RQvUWQmDbj/ajAbSQJ4/U+RJ2WBvTafQdv84gbhi4MFFEijdUGYKCsjMBKiXDValcEJm3NVefaSUihkBmASCK66hnr0IjpnFfqACYqaQzy0tG1YR8EkGPiynztBLjY1bEXB8e+y5UOU+RHiNeDmInU12nEBtUyEeBWgog7CPHPR2p9eSrtppV6Und1Oc8rPcgQEyT5LlxBFNHv3d4oyg0NPf11vddqLsc/4IN7eBHEZjiJ+tNqCWNdUXpEuIEoCIeR35a9U8s3v13PvIZM4U=
  file: curl.framework.zip
  skip_cleanup: true
  on:
    tags: true
